# Generated by Django 5.2 on 2025-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('temat_pracy', models.TextField()),
                ('promotor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('nowy', 'Nowy'), ('w_toku', 'W toku'), ('zakończony', 'Zakończony')], max_length=50)),
            ],
        ),
    ]
