# Generated by Django 5.2 on 2025-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktoranci', '0002_profiluzytkownika'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrzewodDoktorski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doktorant', models.CharField(max_length=200)),
                ('temat', models.TextField()),
                ('promotor', models.CharField(max_length=200)),
                ('data_zlozenia', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
